name: Publish & Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
          config-file: .github/release-please/release-please-config.json
          manifest-file: .github/release-please/manifest.json

      - name: Update Gradle Version
        if: ${{ steps.release.outputs.release_created }}
        run: |
          version="${{ steps.release.outputs.tag_name }}"
          version="${version#v}"
          sed -i "s/^version=.*/version=$version/" gradle.properties

      - name: Set up JDK
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Publish and release to Maven Central
        if: ${{ steps.release.outputs.release_created }}
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
